[package]
name = "yatir-tasks"
version = "0.0.0"
authors = ["Vladimir Stepanenko <vovac12@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
yatir-core = { path = "../../core" }
async-trait = "0.1"
